# Generated by Django 3.0.8 on 2020-08-06 07:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
    ]
