# Generated by Django 3.0.8 on 2020-08-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_reserved_amount'),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'done'), (2, 'canceled'), (3, 'failed')], default=0)),
                ('on_date', models.DateTimeField()),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_payment_in', to='account.Account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_payment_out', to='account.Account')),
                ('transfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled', to='transfer.Transfer')),
            ],
        ),
    ]
